Implemented Raw Data Export for Multiple Cells
jlab-sensing/DirtViz pull request #204
Opened 2024-03-14 02:22 UTC by ay-bh

Implemented enhancements to the "export to csv" functionality on the dashboard. With this update, users can now export raw data for multiple cells as separate CSV files, addressing the issue where previously only aggregated hourly data could be exported for a single cell, resolves #203.  

#### Changes Made:

1. Added a `resample` query parameter to the backend API endpoint `/api/cell/data/${cellId}`, allowing the API to handle raw data export when `resample=none` is specified. This parameter is used to determine whether to perform data resampling or to fetch raw data.

2. Updated the backend database models to handle the new `resample` logic.

3. Revised the `getCellData` schema to include the `resample` parameter, enabling front-end requests to specify the desired resampling strategy.

4. Altered the front-end logic in `DownloadBtn.jsx` to pass the `resample=none` parameter when initiating the data download, ensuring that raw data is exported.

#### Testing Performed:

Manual testing was conducted to ensure the new functionalities work as expected. This includes:

- REST API calls to the endpoint with various resample values to validate backend response.
- Frontend tests for exporting multiple cells' data with different resampling settings to ensure proper CSV file generation.

2024-03-21 00:11 UTC, aaron-wu1 requested changes

2024-03-21 00:11 UTC, aaron-wu1 commented on frontend/src/services/cell.js
Can you also add the default resample value as hourly, if resample isn't passed in

2024-03-21 06:45 UTC, ay-bh commented on frontend/src/services/cell.js
Done

2024-03-21 06:45 UTC, ay-bh commented on backend/api/database/schemas/get_cell_data_schema.py
Done

2024-04-02 04:57 UTC, aaron-wu1 requested changes
marshmallow is already imported with ma so we could use ma.validate instead

2024-04-02 05:10 UTC, ay-bh commented
> marshmallow is already imported with ma so we could use ma.validate instead
@aaron-wu1 We need to import `validate` directly to access Marshmallow's validation functions, which aren't available as attributes of the Marshmallow instance (`ma`).

2024-04-02 05:27 UTC, aaron-wu1 approved these changes

2024-04-02 05:28 UTC, merged