Test branch
jlab-sensing/DirtViz pull request #68
Opened 2023-02-10 00:02 UTC by adunlop621

Added a slider to allow user to choose how much data they want to access, defaulting to one week of data from the current day. Still need to add feature to allow user to type in the desired date range and create separate widgets for the power data and teros data graphs, but this does the job for now.

2023-02-25 21:18 UTC, cjosephson commented
@adunlop621 fix the failing lint check. @jmadden173 have you been able to do a code review for this yet? Do you want to re-assign the review to Aaron?

2023-02-27 17:19 UTC, jmadden173 requested changes
One major aspect that I couldn't find a place to mention in the code itself is that you are still querying all of the data and truncated it to the date range of the slider. To actually make the query faster therefore the website faster, the data should be truncated within the functions `get_teros_data()` and `get_power_data()`.

Summary

- [ ] Fix linting errors
- [ ] Move data truncation to SQL query
- [ ] If applicable, change cutoff index based off of timestamp

One other thing is that this branch also added a history column that wasn't mentioned as part of the PR. For every issue/feature that is being added a new separate branch should be created along with a separate PR.

2023-02-27 17:19 UTC, jmadden173 commented on dirtviz/main.py
> +cutoff = -168
Cutoff for data should not be arbitrary and should be calculated via the timestamp. That way if the timestep changes, this code won't break. For reference the `get_power_data()` and `get_teros_data()` resample the data to an hour.

2023-02-27 17:19 UTC, jmadden173 commented on dirtviz/main.py
> +    title="V/C Measurements",
Why was this changed?

2023-02-27 17:19 UTC, jmadden173 commented on dirtviz/main.py
> +def update_range(attr, old, new):
Add a docstring to this function

2023-02-27 17:19 UTC, jmadden173 commented on import_example_data.py
> +    import_rl_csv("data/soil_20220629-214516_8_long.csv", "examplelogger", "cell1",
Why was this changed? I believe that I used the shorter sample data since that reduces the import time when setting up a local dev env.

2023-02-27 17:19 UTC, jmadden173 commented on dirtviz/main.py
> +            'timestamp': [source_data["timestamp"][i] for i in range(len(source_data["timestamp"])) if source_data["timestamp"][i].timestamp()*1000 > new[0] and source_data["timestamp"][i].timestamp(
I believe this was covered in linting, but this part is extremely hard to read and should be converted into full `for` statements from list comprehension.

2023-03-06 21:27 UTC, adunlop621 commented on dirtviz/main.py
> +    title="V/C Measurements",
Sorry, I was testing something and forgot to change it back

2023-03-06 21:35 UTC, adunlop621 commented on dirtviz/main.py
> +cutoff = -168
Since get_power_data() and get_teros_data() resample the data to an hour, I used -168 as a cutoff point since this would query exactly one week of data (24 hours x 7 days = 168). I could find another way to do this if we're expecting the code to be used with less than a week's worth of data

2023-03-06 21:36 UTC, adunlop621 commented on dirtviz/main.py
> +def update_range(attr, old, new):
Got it!

2023-03-06 21:37 UTC, adunlop621 commented on import_example_data.py
> +    import_rl_csv("data/soil_20220629-214516_8_long.csv", "examplelogger", "cell1",
Ok, got it, I'll change it back

2023-03-06 21:37 UTC, adunlop621 commented on dirtviz/main.py
> +            'timestamp': [source_data["timestamp"][i] for i in range(len(source_data["timestamp"])) if source_data["timestamp"][i].timestamp()*1000 > new[0] and source_data["timestamp"][i].timestamp(
Will do!

2023-08-02 22:33 UTC, closed without merging